### ISSUE TITLE
load_from and data_key not working

### ISSUE THREAD

**Issue by logileifs** [sloria/webargs-starlette#22]
If I use data_key or load_from in my schema the value gets dropped during parsing.
Is there any way to have the value renamed during parsing?

**Comment by sloria** [comment]
Hm, I would expect those to work, given that we [document them](https://github.com/marshmallow-code/webargs/blob/dc2870023ab768e796815cc04d8415695427c320/src/webargs/fields.py#L13) in webargs. Can you post code that reproduces the issue? Also, what version of webargs are you using?

**Comment by logileifs** [comment]
Never mind, I was just misunderstanding the documentation. Sorry about that :)
