### ISSUE TITLE
Why not merge this project into webargs?

### ISSUE THREAD

**Issue by jodusan** [sloria/webargs-starlette#7]
Hi, webargs has support for bunch of frameworks. What am I missing on why this whole repo cant be integrated into webargs?

Thanks

**Comment by sloria** [comment]
I wanted to keep the release schedule for this project independent from webargs. Supporting so many frameworks within webargs core has become burdensome from a maintenance POV, so we've stopped adding new frameworks. 

Also, keeping this project separate allows me experiment with and validate APIs such as `use_annotations` [before they go into webargs core](https://github.com/marshmallow-code/webargs/issues/353).
